[package]
name = "slint-rust-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp"] }
rfd = "0.17.2"
slint = { version = "1.14.1", features = ["image-default-formats"] }

[build-dependencies]
slint-build = "1.14.1"
